### ISSUE TITLE
Usage of abstract components is broken

### ISSUE THREAD

**Issue by BertrandD** [ystia/yorc-a4c-plugin#35]
# Issue Type
* [X] Bug report

## Description

Usage of abstract components is broken

## Expected behavior

I would like to deploy an application using abstract components using A4C matching. 

## Actual behavior

I create an application in A4C, I create the associated resource in the corresponding location, the matching is working very well. In the topology sended to Yorc, the topology is good. Indeed in the `node_template:` section, I have my concrete component inserted by the matching. But in the workflow I have something very strange.

I was expecting to have approximately the same workflow using an abstract component or using a concrete component. But it is not. With the abstract component I have this workflow : 

```yaml
  workflows:
    install:
      steps:
        Compute_install:
          target: Compute
          activities:
            - delegate: install
          on_success:
            - ConsulServer_install
        ConsulServer_install:
          target: ConsulServer
          activities:
            - delegate: install

```

Wich causes this error in Yorc : 

`[2018-08-01T09:23:52.919112565+02:00][DEBUG][test-Environment][install][72018f83-69b5-4412-b239-71b84eb18b1c][ConsulServer][][][][]Step "ConsulServer_install": error details: Unsupported node type "org.ystia.yorc.samples.consul.linux.ansible.nodes.ConsulServer" for a delegate operation
`

Here is the complete topology sended to yorc : 

```yaml
tosca_definitions_version: alien_dsl_2_0_0

metadata:
  template_name: Test
  template_version: 0.1.0-SNAPSHOT
  template_author: ${template_author}

description: ""

imports:
  - org.ystia.yorc.pub/1.0.0-SNAPSHOT/types.yaml
  - org.ystia.ansible.pub/1.0.0-SNAPSHOT/types.yaml
  - <yorc-openstack-types.yml>
  - org.ystia.yorc.linux.ansible/1.0.0-SNAPSHOT/types.yaml
  - org.ystia.yorc.samples.consul.linux.ansible/1.0.0-SNAPSHOT/types.yaml
  - org.ystia.yorc.samples.consul.pub/1.0.0-SNAPSHOT/types.yaml
  - <yorc-types.yml>

topology_template:
  node_templates:
    Compute:
      metadata:
        a4c_edit_x: 103
        a4c_edit_y: "-47"
      type: yorc.nodes.openstack.Compute
      properties:
        image: "7d9bd308-d9c1-4952-a410-95b761672499"
        flavor: 4
        key_pair: yorc
      capabilities:
        endpoint:
          properties:
            credentials: 
              user: root
            secure: true
            protocol: tcp
            network_name: PRIVATE
            initiator: source
        scalable:
          properties:
            min_instances: 1
            max_instances: 1
            default_instances: 1
    ConsulServer:
      type: org.ystia.yorc.samples.consul.linux.ansible.nodes.ConsulServer
      properties:
        install_dnsmasq: true
        mode: server
        download_url: "https://releases.hashicorp.com/consul/1.0.2/consul_1.0.2_linux_amd64.zip"
        install_dir: "/usr/local/bin"
        data_dir: "/var/consul"
        config_dir: "/etc/consul.d"
        datacenter: dc1
        domain: consul
      requirements:
        - hostedOnComputeHost:
            type_requirement: host
            node: Compute
            capability: tosca.capabilities.Container
            relationship: tosca.relationships.HostedOn
      capabilities:
        consul_agent:
          properties:
            api_port: 8500
            protocol: tcp
            secure: false
            network_name: PRIVATE
            initiator: source
  workflows:
    install:
      steps:
        Compute_install:
          target: Compute
          activities:
            - delegate: install
          on_success:
            - ConsulServer_install
        ConsulServer_install:
          target: ConsulServer
          activities:
            - delegate: install
    uninstall:
      steps:
        Compute_uninstall:
          target: Compute
          activities:
            - delegate: uninstall
        ConsulServer_uninstall:
          target: ConsulServer
          activities:
            - delegate: uninstall
          on_success:
            - Compute_uninstall
    start:
      steps:
        ConsulServer_start:
          target: ConsulServer
          activities:
            - delegate: start
        Compute_start:
          target: Compute
          activities:
            - delegate: start
          on_success:
            - ConsulServer_start
    stop:
      steps:
        ConsulServer_stop:
          target: ConsulServer
          activities:
            - delegate: stop
          on_success:
            - Compute_stop
        Compute_stop:
          target: Compute
          activities:
            - delegate: stop

```

## Steps to reproduce the issue

1. Create an application on your A4C with an component that is abstact (but not a compute). You can use the [org.ystia.yorc.samples.consul.pub.nodes.ConsulServer](https://github.com/ystia/forge/tree/develop/org/ystia/consul) component

![bugabstract](https://user-images.githubusercontent.com/5462929/43507456-76ee56e8-956d-11e8-8316-c9caa0edeb7d.png)

```yaml
topology_template:
  node_templates:
    Compute:
      metadata:
        a4c_edit_x: 103
        a4c_edit_y: "-47"
      type: tosca.nodes.Compute
      capabilities:
        scalable:
          properties:
            min_instances: 1
            max_instances: 1
            default_instances: 1
        endpoint:
          properties:
            secure: true
            protocol: tcp
            network_name: PRIVATE
            initiator: source
    ConsulServer:
      type: org.ystia.yorc.samples.consul.pub.nodes.ConsulServer
      properties:
        mode: server
        download_url: "https://releases.hashicorp.com/consul/1.0.2/consul_1.0.2_linux_amd64.zip"
        install_dir: "/usr/local/bin"
        data_dir: "/var/consul"
        config_dir: "/etc/consul.d"
        datacenter: dc1
        domain: consul
      requirements:
        - hostedOnComputeHost:
            type_requirement: host
            node: Compute
            capability: tosca.capabilities.Container
            relationship: tosca.relationships.HostedOn
      capabilities:
        consul_agent:
          properties:
            api_port: 8500
            protocol: tcp
            secure: false
            network_name: PRIVATE
            initiator: source
```

2. Create the resource in the location

![bugabstract2](https://user-images.githubusercontent.com/5462929/43507971-e1cb95e2-956e-11e8-87a1-4c0fb626e25e.png)

3. Deploy the application, and see how it failes

## Alien4Cloud version

2.0.0

## Output of `yorc version`

```
Yorc Server v3.1.0-SNAPSHOT
Revision: "9fd36012fd2a8e93071f958c5e65c7e79a84353d"
```

## Priority

Medium
